import Head from 'next/head'
import Layout from '@/components/Layout'
import Image from 'next/image'
import profilePic from "../../public/images/profile/Thearin.png"
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import HireMe from '@/components/HireMe'
import lightBulb from '../../public/images/svgs/miscellaneous_icons_1.svg';
import { motion } from 'framer-motion'
import TransitionEffect from '@/components/TransitionEffect'
import '../styles/Home.module.css'

const FramerImage = motion(Image);





export default function Home() {
  return (
    <>
      <Head>
        <title>KUCH THEARIN</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect/>
       <main className='flex items-center text-dark w-full min-h-screen dark:text-light'>
        <Layout className='pt-0 md:pt-16 md:inline-bl'>
          <div className='flex items-center justify-between w-full lg:flex-col'>
            <div className='w-1/3 md:w-full'>
              <FramerImage src={profilePic} alt="Kuchthearin" className='w-full h-auto rounded-3xl lg:hidden md:inline-block md:w-full'
               whileHover={{scale:1.05}}
               transition={{duration:0.2}}
               priority
               sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
              />
            </div>
            <div className='w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center'>
              <AnimatedText text="Hi I'M KUCH THEARIN." clasName='text-primary !text-6xl !text-left dark:text-primaryDark
              xl:!text-5xl lg:!text-center lg:!text=6xl md:!text-5xl sm:!text-3xl
              '/>

              <p className='my-4 text-base font-medium md:text-sm sm:text-xs '>
              ជម្រាបសួរពុកម៉ែបងប្អូនទាំងអស់គ្នា🙏
              ខ្ញុំឈ្មោះ គុជ​​ ធារិន។ ខ្ញុំជានិស្សិតសាកលវិទ្យាល័យ ​(RUPP) ហើយខ្ញុំបង្កើតគេហទំព័រនេះឡើងក្នុងគោលបំណងចែករំលែកពីចំណេះដឹងផ្សេងៗដែលខ្ញុំចេះ។
              </p>
              <div className='flex items-center self-start mt-2 lg:salf-center'>
                <Link href="/kuchthearin.pdf" target={"_black"}
                className='flex items-center bg-primary text-light p-2.5 px-6
                rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                border-2 border-solid border-transparent hover:border-primary
                dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-primaryDark
                hover:dark:border-primaryDark md:p-2 md:px-4 md:text-base
                '
                download={true}
                >My CV 
                </Link>
                <Link href="mailto:Kuchthearxnn@gmail.com" target={"_black"}
                className="ml-4 text-lg font-medium capitalize text-primary underline dark:text-light md:text-base"
                >Contact</Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe/>
        <div className='absolute right-8 bottom-8 inline-block w-24 md:hidden'>
          <FramerImage src={lightBulb} alt='kuchthearin' className='w-full h-auto'
          whileHover={{scale:1.05}}
          transition={{duration:0.2}}/>
        </div>
      
       </main>
    </>
  )
}
